### PR TITLE
Code formatting with black

### PR DESCRIPTION
**Pull request by rnixx**
I'm a big fan of uniform code formatting. I used black to format the respository.

@JohnSumskas @tshirtman do we agree to use black for this code base?

### CODE REVIEW

**Review by AndreMiras — APPROVED** [review]
I would say if you're about to use black on this project maybe then you should share your black settings if you have. Also you may want to add it to the CI. Otherwise people would always put unformatted code and you would always create a commit on top just to format it (which generates noise on the log/blame).
What do you think?

**Comment by rnixx** [comment]
My policy is simple. Use default settings. Other opinions welcome ;).

Once we agree to use black we can add it into CI.

**Comment by JohnSumskas** [comment]
I'm happy to use black to format the repository.

**Comment by rnixx** [comment]
@AndreMiras after digging around a git pre commit hook seems the most appropriate way for hooking up black formatting.

Someshing like

.git/hooks/pre-commit

    #!/bin/sh
    set -e

    files=`git diff --staged --name-only --diff-filter=d -- "*.py"`

    for file in $files; do
      black $file
      git add $file
    done

**Comment by AndreMiras** [comment]
Yeah I don't know how to feel about formatting code in hooks, because it may screw up your formatting without you noticing it. But if you like it that way I don't mind
I think I would have tried to avoid the for loop by doing (untested):
```
black $files
git add $files
```

**Comment by rnixx** [comment]
> Yeah I don't know how to feel about formatting code in hooks, because it may screw up your formatting without you noticing it

Valid point. OK, i think, to not overcomplicate things, let's write it down somewhere that this repo is black formatted, and if someone opens an unformatted PR he/she needs to run black manually and squash the commits.

**Pull request merged**
